[package]
name = "lox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
    strum = "0.26.3"
    strum_macros = "0.26.3"
    thiserror = "2.0.9"
    smartstring = "1.0.1"
