[package]
name = "lox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
    phf = {version = "0.11", features = ["macros"]}
    strum = "0.26.3"
    strum_macros = "0.26.3"
    thiserror = "1.0.63"
